# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad4f6bce00289511cda798136cce0688e83eac5751c4c7632f1f3138f0228a6740ee6236bdb4f4b2401b468c5428dab4ce1f3fdad1bac1405c8b0bffa6df4404

test:
  secret_key_base: 3b19ae8e51fa57012847507e325af19edc4fae229842d5986735a170dfe77747a0c0410c7341be59bf6d659b6d5723e05382fda2c4a1d8860b978aea02c6884c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
